#!/usr/bin/env python3
"""Generate README SVG charts: daily commits and lines of code by language."""

from __future__ import annotations

import math
import subprocess
from collections import Counter
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "assets" / "readme"
TZ = timezone(timedelta(hours=8))
COMMIT_DAYS = 30

SKIP_DIRS = {
    ".git",
    ".vs",
    ".cache",
    ".claude",
    "build",
    "out",
    "site",
    "3rdparty",
    "vcpkg_installed",
    "_deps",
    "CMakeFiles",
    "node_modules",
}

LANG_BY_EXT = {
    ".c": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".cxx": "C++",
    ".h": "C++",
    ".hh": "C++",
    ".hpp": "C++",
    ".hxx": "C++",
    ".hlsl": "HLSL",
    ".glsl": "GLSL",
    ".wgsl": "WGSL",
    ".py": "Python",
    ".cmake": "CMake",
    ".qml": "QML",
    ".js": "JavaScript",
    ".tsx": "TypeScript",
    ".mts": "TypeScript",
    ".cts": "TypeScript",
    ".rs": "Rust",
    ".go": "Go",
}

SPECIAL_FILES = {
    "CMakeLists.txt": "CMake",
}

LANG_COLORS = {
    "C++": "#f34b7d",
    "C": "#555555",
    "CMake": "#da3434",
    "HLSL": "#aace60",
    "GLSL": "#5686a5",
    "WGSL": "#1a5e9a",
    "Python": "#3572a5",
    "QML": "#44a51c",
    "JavaScript": "#f1e05a",
    "TypeScript": "#3178c6",
    "Rust": "#dea584",
    "Go": "#00add8",
    "Other": "#8b949e",
}

CARD_BG = "#0d1117"
CARD_BORDER = "#30363d"
TEXT = "#c9d1d9"
MUTED = "#8b949e"
GRID = "#21262d"
BAR = "#3fb950"
FONT = (
    "-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans SC',"
    "'PingFang SC','Microsoft YaHei',sans-serif"
)


def xml(text: object) -> str:
    return escape(str(text), {"'": "&apos;", '"': "&quot;"})


def count_lines(path: Path) -> int:
    try:
        raw = path.read_bytes()
    except OSError:
        return 0
    if b"\0" in raw:
        return 0
    text = raw.decode("utf-8", errors="replace")
    if not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def language_counts() -> list[tuple[str, int]]:
    counts: Counter[str] = Counter()
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        lang = SPECIAL_FILES.get(path.name)
        if lang is None:
            lang = LANG_BY_EXT.get(path.suffix.lower())
        if lang is None:
            continue
        n = count_lines(path)
        if n:
            counts[lang] += n
    ranked = counts.most_common()
    if len(ranked) > 8:
        head, tail = ranked[:7], ranked[7:]
        ranked = head + [("Other", sum(n for _, n in tail))]
    return ranked


def git_output(*args: str) -> str:
    return subprocess.check_output(
        ["git", *args],
        cwd=ROOT,
        text=True,
        encoding="utf-8",
        errors="replace",
    )


def daily_commits(days: int = COMMIT_DAYS) -> list[tuple[date, int]]:
    end = datetime.now(TZ).date()
    start = end - timedelta(days=days - 1)
    counts = {start + timedelta(days=i): 0 for i in range(days)}
    since = start.isoformat()
    log = git_output("log", "--format=%aI", f"--since={since}")
    for line in log.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            when = datetime.fromisoformat(line).astimezone(TZ).date()
        except ValueError:
            continue
        if when in counts:
            counts[when] += 1
    return sorted(counts.items())


def nice_max(value: int) -> int:
    if value <= 1:
        return 1
    magnitude = 10 ** max(0, int(math.floor(math.log10(value))))
    for step in (1, 2, 5, 10):
        candidate = step * magnitude
        if candidate >= value:
            return candidate
    return magnitude * 10


def card(width: int, height: int, body: str) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
        f'height="{height}" viewBox="0 0 {width} {height}" role="img">\n'
        f"  <!-- generated by scripts/readme_stats.py; do not edit -->\n"
        f'  <rect x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" '
        f'rx="12" fill="{CARD_BG}" stroke="{CARD_BORDER}"/>\n'
        f"{body}"
        f"</svg>\n"
    )


def title_block(title: str, subtitle: str) -> str:
    return (
        f'  <text x="24" y="32" fill="{TEXT}" font-size="16" font-weight="600" '
        f'font-family="{FONT}">{xml(title)}</text>\n'
        f'  <text x="24" y="52" fill="{MUTED}" font-size="12" '
        f'font-family="{FONT}">{xml(subtitle)}</text>\n'
    )


def commits_svg(series: list[tuple[date, int]]) -> str:
    width, height = 840, 240
    plot_x, plot_y, plot_w, plot_h = 48, 68, 768, 132
    total = sum(n for _, n in series)
    peak = max((n for _, n in series), default=0)
    y_max = nice_max(peak)
    n = len(series)
    gap = 3
    bar_w = (plot_w - gap * (n - 1)) / n if n else plot_w
    today = datetime.now(TZ).strftime("%Y-%m-%d %H:%M")

    parts = [
        title_block(
            "每日提交",
            f"最近 {COMMIT_DAYS} 天 · 共 {total} 次 · 更新于 {today} CST",
        )
    ]
    for frac, label in ((0, str(y_max)), (0.5, str(y_max // 2)), (1, "0")):
        y = plot_y + plot_h * frac
        parts.append(
            f'  <line x1="{plot_x}" y1="{y:.1f}" x2="{plot_x + plot_w}" '
            f'y2="{y:.1f}" stroke="{GRID}" stroke-width="1"/>\n'
        )
        parts.append(
            f'  <text x="{plot_x - 8}" y="{y + 4:.1f}" fill="{MUTED}" '
            f'font-size="10" text-anchor="end" font-family="{FONT}">'
            f"{xml(label)}</text>\n"
        )

    for i, (day, count) in enumerate(series):
        x = plot_x + i * (bar_w + gap)
        h = 0 if y_max == 0 else plot_h * (count / y_max)
        h = max(h, 2)
        y = plot_y + plot_h - h
        color = BAR if count else GRID
        parts.append(
            f'  <rect x="{x:.2f}" y="{y:.2f}" width="{bar_w:.2f}" '
            f'height="{h:.2f}" rx="2" fill="{color}">\n'
            f"    <title>{xml(day.isoformat())}: {count}</title>\n"
            f"  </rect>\n"
        )

    label_idx = {0, n // 2, n - 1} if n else set()
    for i in sorted(label_idx):
        day, _ = series[i]
        x = plot_x + i * (bar_w + gap) + bar_w / 2
        parts.append(
            f'  <text x="{x:.1f}" y="{plot_y + plot_h + 18}" fill="{MUTED}" '
            f'font-size="10" text-anchor="middle" font-family="{FONT}">'
            f"{xml(day.strftime('%m-%d'))}</text>\n"
        )
    return card(width, height, "".join(parts))


def languages_svg(rows: list[tuple[str, int]]) -> str:
    list_y, row_h = 78, 22
    width = 840
    height = max(248, list_y + max(len(rows), 1) * row_h + 28)
    total = sum(n for _, n in rows) or 1
    today = datetime.now(TZ).strftime("%Y-%m-%d %H:%M")
    parts = [
        title_block(
            "各语言代码行数",
            f"共 {total:,} 行 · 不含 3rdparty / 构建产物 · 更新于 {today} CST",
        )
    ]

    cx, cy, radius, stroke = 110, 72 + (height - 72) / 2, 52, 18
    circ = 2 * math.pi * radius
    offset = 0.0
    parts.append(
        f'  <circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" '
        f'stroke="{GRID}" stroke-width="{stroke}"/>\n'
    )
    for name, n in rows:
        color = LANG_COLORS.get(name, LANG_COLORS["Other"])
        dash = circ * (n / total)
        parts.append(
            f'  <circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" '
            f'stroke="{color}" stroke-width="{stroke}" '
            f'stroke-dasharray="{dash:.3f} {circ:.3f}" '
            f'stroke-dashoffset="{-offset:.3f}" '
            f'transform="rotate(-90 {cx} {cy})"/>\n'
        )
        offset += dash

    parts.append(
        f'  <text x="{cx}" y="{cy - 4}" fill="{TEXT}" font-size="18" '
        f'font-weight="600" text-anchor="middle" font-family="{FONT}">'
        f"{total:,}</text>\n"
        f'  <text x="{cx}" y="{cy + 16}" fill="{MUTED}" font-size="11" '
        f'text-anchor="middle" font-family="{FONT}">行</text>\n'
    )

    list_x, list_y = 200, 78
    row_h = 22
    bar_x = 430
    bar_w = 280
    for i, (name, n) in enumerate(rows):
        y = list_y + i * row_h
        color = LANG_COLORS.get(name, LANG_COLORS["Other"])
        pct = 100.0 * n / total
        fill_w = bar_w * (n / total)
        parts.append(
            f'  <rect x="{list_x}" y="{y}" width="10" height="10" rx="2" '
            f'fill="{color}"/>\n'
            f'  <text x="{list_x + 18}" y="{y + 10}" fill="{TEXT}" '
            f'font-size="13" font-family="{FONT}">{xml(name)}</text>\n'
            f'  <rect x="{bar_x}" y="{y + 1}" width="{bar_w}" height="8" '
            f'rx="4" fill="{GRID}"/>\n'
            f'  <rect x="{bar_x}" y="{y + 1}" width="{fill_w:.2f}" height="8" '
            f'rx="4" fill="{color}"/>\n'
            f'  <text x="{bar_x + bar_w + 12}" y="{y + 10}" fill="{MUTED}" '
            f'font-size="12" font-family="{FONT}">'
            f"{n:,}  ({pct:.1f}%)</text>\n"
        )
    return card(width, height, "".join(parts))


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    commits = daily_commits()
    languages = language_counts()
    (OUT_DIR / "commits.svg").write_text(commits_svg(commits), encoding="utf-8")
    (OUT_DIR / "languages.svg").write_text(
        languages_svg(languages), encoding="utf-8"
    )
    loc = ", ".join(f"{name} {n}" for name, n in languages)
    print(f"wrote {OUT_DIR / 'commits.svg'}")
    print(f"wrote {OUT_DIR / 'languages.svg'}")
    print(f"languages: {loc}")


if __name__ == "__main__":
    main()
