<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tamias.Host</RootNamespace>
    <AssemblyName>Tamias.Host</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tamias.Api\Tamias.Api.csproj" />
  </ItemGroup>
</Project>
